#ifndef INPUT_CODES_H
#define INPUT_CODES_H

namespace Input {

    enum class Key {
        Unknown = -1,
        Space,
        Apostrophe,
        Comma,
        Minus,
        Period,
        Slash,
        _0,
        _1,
        _2,
        _3,
        _4,
        _5,
        _6,
        _7,
        _8,
        _9,
        Semicolon,
        Equal,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        LeftBracket,
        Backslash,
        RightBracket,
        GraveAccent,
        World1,
        World2,
        Escape,
        Enter,
        Tab,
        Backspace,
        Insert,
        Delete,
        Right,
        Left,
        Down,
        Up,
        PageUp,
        PageDown,
        Home,
        End,
        CapsLock,
        ScrollLock,
        NumLock,
        PrintScreen,
        Pause,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        F13,
        F14,
        F15,
        F16,
        F17,
        F18,
        F19,
        F20,
        F21,
        F22,
        F23,
        F24,
        F25,
        Kp0,
        Kp1,
        Kp2,
        Kp3,
        Kp4,
        Kp5,
        Kp6,
        Kp7,
        Kp8,
        Kp9,
        KpDecimal,
        KpDivide,
        KpMultiply,
        KpSubtract,
        KpAdd,
        KpEnter,
        KpEqual,
        LeftShift,
        LeftControl,
        LeftAlt,
        LeftSuper,
        RightShift,
        RightControl,
        RightAlt,
        RightSuper,
        Menu
    };

    enum class Mouse {
        Button1 = 0,
        Button2 = 1,
        Button3 = 2,
        Button4 = 3,
        Button5 = 4,
        Button6 = 5,
        Button7 = 6,
        Button8 = 7,
        Left = Button1,
        Right = Button2,
        Middle = Button3
    };

    enum class Gamepad {
        ButtonA = 0,
        ButtonB = 1,
        ButtonX = 2,
        ButtonY = 3,
        ButtonLeftBumper = 4,
        ButtonRightBumper = 5,
        ButtonBack = 6,
        ButtonStart = 7,
        ButtonGuide = 8,
        ButtonLeftThumb = 9,
        ButtonRightThumb = 10,
        ButtonDpadUp = 11,
        ButtonDpadRight = 12,
        ButtonDpadDown = 13,
        ButtonDpadLeft = 14,
        Cross = ButtonA,
        Circle = ButtonB,
        Square = ButtonX,
        Triangle = ButtonY
    };

    enum class Action {
        Release = 0,
        Press = 1,
        Repeat = 2
    };

    enum class CursorMode {
        Normal,
        Hidden,
        Locked,
        LockedHidden,
        Disabled
    };
}

#endif
