# - Try to find Assimp
# Once done, this will define
#
# ASSIMP_FOUND - system has Assimp
# ASSIMP_INCLUDE_DIR - the Assimp include directories
# ASSIMP_LIBRARIES - link these to use Assimp
FIND_PACKAGE(assimp CONFIG QUIET)
IF(TARGET assimp::assimp)
	SET(ASSIMP_FOUND TRUE)
	SET(ASSIMP_LIBRARIES assimp::assimp)
	GET_PROPERTY(ASSIMP_INCLUDE_DIR TARGET assimp::assimp PROPERTY INTERFACE_INCLUDE_DIRECTORIES)
	IF(NOT TARGET ASSIMP::ASSIMP)
		ADD_LIBRARY(ASSIMP::ASSIMP INTERFACE IMPORTED)
		SET_TARGET_PROPERTIES(ASSIMP::ASSIMP PROPERTIES
			INTERFACE_LINK_LIBRARIES assimp::assimp
		)
	ENDIF()
	RETURN()
ENDIF()

FIND_PATH( ASSIMP_INCLUDE_DIR assimp/mesh.h
	/usr/include
	/usr/local/include
	/opt/local/include
	/opt/homebrew/include
)
FIND_LIBRARY( ASSIMP_LIBRARY
	NAMES assimp-vc143-mt assimp
	PATHS
	/usr/lib64
	/usr/lib
	/usr/local/lib
	/opt/local/lib
	/opt/homebrew/lib
)
IF(ASSIMP_INCLUDE_DIR AND ASSIMP_LIBRARY)
	SET( ASSIMP_FOUND TRUE )
	SET( ASSIMP_LIBRARIES ${ASSIMP_LIBRARY} )
ENDIF(ASSIMP_INCLUDE_DIR AND ASSIMP_LIBRARY)
IF(ASSIMP_FOUND)
	IF(NOT ASSIMP_FIND_QUIETLY)
	MESSAGE(STATUS "Found ASSIMP: ${ASSIMP_LIBRARY}")
	ENDIF(NOT ASSIMP_FIND_QUIETLY)
	IF(NOT TARGET ASSIMP::ASSIMP)
		ADD_LIBRARY(ASSIMP::ASSIMP UNKNOWN IMPORTED)
		SET_TARGET_PROPERTIES(ASSIMP::ASSIMP PROPERTIES
			IMPORTED_LOCATION "${ASSIMP_LIBRARY}"
			INTERFACE_INCLUDE_DIRECTORIES "${ASSIMP_INCLUDE_DIR}"
		)
	ENDIF()
ELSE(ASSIMP_FOUND)
	IF(ASSIMP_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find libASSIMP")
	ENDIF(ASSIMP_FIND_REQUIRED)
ENDIF(ASSIMP_FOUND)
